import { resolve, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { homedir } from "node:os";

// ---------------------------------------------------------------------------
// Skill loader — resolves from the CLI package's own skills/ directory
// ---------------------------------------------------------------------------

const SKILL_NAMES = ["vibeo-core", "vibeo-audio", "vibeo-effects", "vibeo-extras", "vibeo-rendering", "vibeo-editor", "vibeo-tiktok"];

async function loadSkills(): Promise<Record<string, string>> {
  // Resolve from this file's location — skills/ is shipped alongside dist/ in the npm package
  const thisFile = fileURLToPath(import.meta.url);
  const thisDir = dirname(thisFile);

  // From dist/commands/install-skills.js → ../../skills
  // From src/commands/install-skills.ts → ../../skills
  const candidates = [
    join(thisDir, "..", "..", "skills"),       // from dist/commands/ or src/commands/
    join(thisDir, "..", "..", "..", "skills"),  // from deeper nesting
    join(process.cwd(), "skills"),             // from project root
  ];

  for (const dir of candidates) {
    const skills: Record<string, string> = {};
    let found = true;

    for (const name of SKILL_NAMES) {
      const path = join(dir, name, "SKILL.md");
      if (existsSync(path)) {
        skills[name] = await readFile(path, "utf-8");
      } else {
        found = false;
        break;
      }
    }

    if (found) return skills;
  }

  throw new Error(
    "Could not find skill files. Make sure the @vibeo/cli package is installed correctly.",
  );
}


// ---------------------------------------------------------------------------
// LLM tool targets
// ---------------------------------------------------------------------------

interface Target {
  name: string;
  description: string;
  install: (skills: Record<string, string>, cwd: string) => Promise<string[]>;
}

const home = homedir();

const TARGETS: Target[] = [
  {
    name: "claude",
    description: "Claude Code (~/.claude/skills/<name>/SKILL.md + project .claude/skills/<name>/SKILL.md)",
    async install(skills, cwd) {
      const files: string[] = [];

      // Global skills directory — each skill in its own dir with SKILL.md
      const globalDir = join(home, ".claude", "skills");
      for (const [name, content] of Object.entries(skills)) {
        const skillDir = join(globalDir, name);
        await mkdir(skillDir, { recursive: true });
        const path = join(skillDir, "SKILL.md");
        await writeFile(path, content);
        files.push(path);
      }

      // Project-level .claude/skills/<name>/SKILL.md
      const projectDir = join(cwd, ".claude", "skills");
      for (const [name, content] of Object.entries(skills)) {
        const skillDir = join(projectDir, name);
        await mkdir(skillDir, { recursive: true });
        const path = join(skillDir, "SKILL.md");
        await writeFile(path, content);
        files.push(path);
      }

      return files;
    },
  },
  {
    name: "codex",
    description: "OpenAI Codex CLI (project AGENTS.md)",
    async install(skills, cwd) {
      const combined = Object.values(skills).join("\n\n---\n\n");
      const path = join(cwd, "AGENTS.md");
      const header = "# Vibeo — Agent Instructions\n\nThis file is auto-generated by `vibeo install-skills`. It helps Codex CLI understand the Vibeo framework.\n\n";
      await writeFile(path, header + combined);
      return [path];
    },
  },
  {
    name: "cursor",
    description: "Cursor (.cursor/rules/*.mdc)",
    async install(skills, cwd) {
      const dir = join(cwd, ".cursor", "rules");
      await mkdir(dir, { recursive: true });
      const files: string[] = [];
      for (const [name, content] of Object.entries(skills)) {
        const mdcContent = `---\ndescription: ${name} skill for Vibeo video framework\nglobs: **/*.{ts,tsx}\nalwaysApply: false\n---\n\n${content}`;
        const path = join(dir, `${name}.mdc`);
        await writeFile(path, mdcContent);
        files.push(path);
      }
      return files;
    },
  },
  {
    name: "gemini",
    description: "Gemini CLI (GEMINI.md)",
    async install(skills, cwd) {
      const combined = Object.values(skills).join("\n\n---\n\n");
      const path = join(cwd, "GEMINI.md");
      const header = "# Vibeo — Gemini Instructions\n\nThis file is auto-generated by `vibeo install-skills`. It helps Gemini CLI understand the Vibeo framework.\n\n";
      await writeFile(path, header + combined);
      return [path];
    },
  },
  {
    name: "opencode",
    description: "OpenCode (AGENTS.md)",
    async install(skills, cwd) {
      // OpenCode also reads AGENTS.md — same as codex, but we don't double-write
      const path = join(cwd, "AGENTS.md");
      if (existsSync(path)) return []; // Already written by codex target
      const combined = Object.values(skills).join("\n\n---\n\n");
      const header = "# Vibeo — Agent Instructions\n\nThis file is auto-generated by `vibeo install-skills`. It helps AI agents understand the Vibeo framework.\n\n";
      await writeFile(path, header + combined);
      return [path];
    },
  },
  {
    name: "aider",
    description: "Aider (.aider.conf.yml conventions file reference)",
    async install(skills, cwd) {
      const combined = Object.values(skills).join("\n\n---\n\n");
      const path = join(cwd, ".aider.vibeo.md");
      await writeFile(path, combined);
      return [path];
    },
  },
];

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function installSkills(
  targets: string[],
  cwd: string,
): Promise<{ installed: Record<string, string[]> }> {
  const skills = await loadSkills();
  const installed: Record<string, string[]> = {};

  const selectedTargets =
    targets.length === 0
      ? TARGETS // all
      : TARGETS.filter((t) => targets.includes(t.name));

  if (selectedTargets.length === 0) {
    throw new Error(
      `No matching targets. Available: ${TARGETS.map((t) => t.name).join(", ")}`,
    );
  }

  for (const target of selectedTargets) {
    const files = await target.install(skills, cwd);
    if (files.length > 0) {
      installed[target.name] = files;
    }
  }

  return { installed };
}

export const AVAILABLE_TARGETS = TARGETS.map((t) => ({
  name: t.name,
  description: t.description,
}));
